$schema: "https://json-schema.org/draft/2020-12/schema"
description: main configuration schema for the workflow
properties:
  sample_sheet:
    type: string
    description: path to sample-sheet CSV file
  sample_folder:
    type: string
    description: path to sample folder

required:
  - sample_sheet
  - sample_folder